datasource:
  #  连接地址（解决UTF-8中文乱码问题 + 时区校正）
  #  rewriteBatchedStatements=true 开启批处理模式）
  url: jdbc:postgresql://127.0.0.1:5432/streamwise_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
  #  用户名
  username: streamwise
  #  密码
  password: streamwise
  #  连接驱动名称
  driver-class-name: org.postgresql.Driver
  hikari:
    pool-name: Hikari
    maximum-pool-size: 10
    auto-commit: true
    idle-timeout: 0
    max-lifetime: 1800000
    connection-timeout: 300000
    validationTimeout: 300000
    connection-test-query: SELECT 1
