server:
  port: 8000
spring:
  application:
    name: emsp-service
profiles:
  active: dev
main:
  allow-circular-references: true
  allow-bean-definition-overriding: true
mvc:
  pathmatch:
    matching-strategy: ant_path_matcher