server:
  port: ${PORT:8080}
spring:
  application:
    name: emsp-service
  datasource:
    url: jdbc:postgresql://emspdb.cvuea2cs0p8i.us-east-2.rds.amazonaws.com:5432/postgres
    username: ${{ secrets.AWS_DB_USERNAME }}
    password: ${{ secrets.AWS_DB_PASSWORD }}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Hikari
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 0
      max-lifetime: 1800000
      connection-timeout: 300000
      validationTimeout: 300000
      connection-test-query: SELECT 1