server:
  port: ${PORT:8080}
spring:
  application:
    name: emsp-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml   # XML 文件放在 resources/mapper 目录下
  type-aliases-package: com.ethan.emsp.infrastructure.persistence.po
  global-config:
    db-config:
      id-type: assign_id   # 雪花算法 ID 策略
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl